apiVersion: v1
kind: Namespace
metadata:
  name: go-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  namespace: go-app
  labels:
    app: go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
        - name: go-app
          image: silva4g/go-deployment:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: go-app
spec:
  selector:
    app: go
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort
---

