apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  namespace: go-app
  labels:
    app: go
    name: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
        - name: go-app
          image: silva4g/go-deployment:v1
          ports:
            - containerPort: 8080