apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: go-app
spec:
  selector:
    app: go
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort